version: '2'
services:
  redis-master:
    image: be-redis:latest
    command: --port 16379
    ports:
      - "16379:16379"
  redis-slave:
    image: be-redis:latest
    command: --port 6380
    ports:
      - "6380:6380"
  sentinel-a:
    image: be-redis:latest
    command: /etc/redis/sentinel.conf --sentinel
    ports:
      - 26379
  sentinel-b:
    image: be-redis:latest
    command: /etc/redis/sentinel.conf --sentinel
    ports:
      - 26379
  sentinel-c:
    image: be-redis:latest
    command: /etc/redis/sentinel.conf --sentinel
    ports:
      - 26379
