version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - certdata:/mnt
    links:
      - certbot
  certbot:
    build: ./certbot
    expose:
      - "80"
    volumes:
      - certdata:/mnt
volumes:
  certdata:
